services:
  - type: web
    name: bixby
    repo: https://github.com/c-o-d-e-xx/WhatsBixby.git
    branch: master
    env: docker
    dockerfilePath: lib/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false
        required: true
