/* Copyright (C) 2025 Codex.
Licensed under the MIT License;
you may not use this file except in compliance with the License.
Codex - Ziyan
*/

const { Bixby, commands } = require("./events");
const config = require("../config");
const Greetings = require("./greetings");
const { serialize, downloadMedia } = require("./serialize");

const {
  getMemoryUsage,
  overrideConsoleLogs,
  m3u82Mp4,
  buffToFile,
  WriteSession,
  fetchWithRetry,
  removeBg,
  validatAndSaveDeleted,
  textToImg,
  readQr,
  createInteractiveMessage,
  ffmpeg,
  toAudio,
  toPTT,
  toVideo,
  getBuffer,
  decodeJid,
  FiletypeFromUrl,
  extractUrlFromMessage,
  removeCommand,
  igdl,
  aiImage,
  getJson,
  parseTimeToSeconds,
  isAdmin,
  webp2mp4,
  webp2png,
  parseJid,
  parsedJid,
  isIgUrl,
  isUrl,
  getUrl,
  qrcode,
  secondsToDHMS,
  formatBytes,
  clockString,
  runtime,
  validateQuality,
  AddMp3Meta,
  Bitly,
  isNumber,
  getRandom,
  findMusic,
  MimeTypes,
  UpdateLocal,
  fromMe
} = require("./function");


module.exports = {  
  isPrivate: config.WORK_TYPE.toLowerCase() === "private",
  Bixby,
  commands,
  Function: Bixby,
  Greetings,
  serialize,
  downloadMedia,
  getMemoryUsage,
  overrideConsoleLogs,
  m3u82Mp4,
  buffToFile,
  WriteSession,
  fetchWithRetry,
  removeBg,
  validatAndSaveDeleted,
  textToImg,
  readQr,
  createInteractiveMessage,
  ffmpeg,
  toAudio,
  toPTT,
  toVideo,
  getBuffer,
  decodeJid,
  FiletypeFromUrl,
  extractUrlFromMessage,
  removeCommand,
  igdl,
  aiImage,
  getJson,
  parseTimeToSeconds,
  isAdmin,
  webp2mp4,
  webp2png,
  parseJid,
  parsedJid,
  isIgUrl,
  isUrl,
  getUrl,
  qrcode,
  secondsToDHMS,
  formatBytes,
  clockString,
  runtime,
  validateQuality,
  AddMp3Meta,
  Bitly,
  isNumber,
  getRandom,
  findMusic,
  MimeTypes,
  UpdateLocal,
  fromMe,
};
